default = "#FF00FF"
background = "#08080D"
ui_view = "#085159"
game_view = "#5F4A8C"

depth_text = "#CB62A8"
gold_text = "#D9886A"

drill = "#FEF375"
vision_circle = "#FEF375"

fuel_back = "#5C4482"
fuel_front = "#CB62A8"

iron = "#EA795D"
rock = "#444444"

[resources]
Iron = "#EA795D"

[nodes]
power = "#3BD97F"
fuel = "#80DBF7"

[nodes.connections]
Blue = "#6079DC"
