name: Deploy
on: push

permissions:
  contents: write

jobs:
  build-web:
    name: Build (Web)
    runs-on: ubuntu-latest
    container: ghcr.io/geng-engine/cargo-geng@sha256:65384ff654422795fb53780fcb9096f89ac44cf5f44d5fb6662e25ec258b90c3
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: Swatinem/rust-cache@v2
      - run: cargo geng build --release --platform web
      - name: Upload artifacts (web)
        uses: actions/upload-artifact@v4
        with:
          name: web
          path: target/geng

  deploy-pages:
    name: Deploy Github Pages
    if: github.ref == 'refs/heads/main' && github.repository_owner == 'nertsal'
    runs-on: ubuntu-latest
    needs:
      - build-web
    permissions:
      contents: write
    environment:
      name: main
      url: https://nertsal.github.io/drillraph
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
      - name: Deploy GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: web

  deploy-itch:
    name: Deploy Itch
    if: github.ref == 'refs/heads/main' && github.repository_owner == 'nertsal'
    runs-on: ubuntu-latest
    needs:
      - build-web
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
      - name: Upload itch.io (Web)
        uses: josephbmanley/butler-publish-itchio-action@master
        env:
          BUTLER_CREDENTIALS: ${{ secrets.BUTLER_CREDENTIALS }}
          CHANNEL: html5
          ITCH_GAME: drillraph
          ITCH_USER: nertsal
          PACKAGE: web
